docs:
	# Build the default builder's Sass.
	if [[ ! -e ./builder/handlebars/node_modules/.bin/node-sass ]]; then cd builder/handlebars && npm install; fi
	cd builder/handlebars && npm run-script sass

	# Build the twig builder's Sass.
	if [[ ! -e ./builder/twig/node_modules/.bin/node-sass ]]; then cd builder/twig && npm install; fi
	cd builder/twig && npm run-script sass

	# Build the kss-node demo.
	./bin/kss --destination gh-pages --demo
	# Build the JS docs.
	echo && echo "Building JavaScript documentation with jsdoc…" && echo
	rm -r ./gh-pages/api/master
	./node_modules/.bin/jsdoc --configure ./gh-pages/api-jsdoc-conf.json
	echo
	./node_modules/.bin/jsdoc --configure ./gh-pages/api-jsdoc-conf.json --destination ./gh-pages/api/master/internals/ --readme ./gh-pages/api-internals.md --access all
	# Clean up the JS docs.
	for HTMLDOC in ./gh-pages/api/*/*.html ./gh-pages/api/*/*/*.html; do cat $$HTMLDOC | sed 's/<title>JSDoc: /<title>KSS JavaScript API: /' | sed -E 's/(Documentation generated by .+<\/a>).+/\1/' > $$HTMLDOC.tmp; mv $$HTMLDOC.tmp $$HTMLDOC; done

.PHONY: docs
